parameters:
  - name: name
    type: string
    default: ''

  - name: steps
    type: stepList
    default: []

  - name: images
    type: object
    default: [windows, ubuntu, macos]

  - name: pythonVersions
    type: object
    default: ['3.5', '3.6', '3.7', '3.8']

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: $(os)
    strategy:
      maxParallel: 6
      matrix:
        ${{ each image in parameters.images }}:
          ${{ each pythonVersion in parameters.pythonVersions }}:
            ${{ format('{0} {1}', image, pythonVersion) }}:
              python_version: ${{ pythonVersion }}
              os: ${{ image }}-latest
              platform: ${{ image }}

    steps:
      - powershell: git config --global core.autocrlf false
        displayName: $(System.JobName) git config core.autocrlf

      - checkout: self

      - template: /.ci/templates/install-project.yaml
        parameters:
          python_version: $(python_version)

      - ${{ each s in parameters.steps }}:
          - ${{ s }}
