parameters:
  - name: name
    type: string
    default: ""

  - name: steps
    type: stepList
    default: []

  - name: matrix
    type: object
    default:
      images: ["windows", "ubuntu", "macos"]
      pythonVersions: ["3.5", "3.6", "3.7", "3.8"]

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: "$(os)"
    strategy:
      maxParallel: 6
      matrix:
        ${{ each image in parameters.matrix.images }}:
          ${{ each pythonVersion in parameters.matrix.pythonVersions }}:
            ${{ format('{0} py{1}', image, pythonVersion) }}:
              python_version: ${{ pythonVersion }}
              os: ${{ image }}-latest

    steps:
      - template: /.ci/templates/install-project.yaml
        parameters:
          python_version: $(python_version)

      - ${{ each s in parameters.steps }}:
          - ${{ s }}
