# specific branch build with batching
trigger:
  branches:
    include:
      - '*'
    exclude:
      - renovate/*

resources:
  repositories:
    - repository: trim21
      type: github
      endpoint: github
      name: Trim21/azure-pipeline-templates
      ref: refs/tags/v0.0.5

stages:
  - stage: Lint
    jobs:
      - template: ./jobs/lint.yaml
  - stage: Test
    jobs:
      - template: ./jobs/test.yaml
