jobs:
  - template: /.ci/templates/job.yaml
    parameters:
      name: Binary
      pythonVersions: ['3.7']
      images:
        - windows
        - ubuntu
#        - "macos"
      steps:
        - script: pyinstaller bgmi.spec

        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: ./dist
            includeRootFolder: false
            archiveFile: $(Build.ArtifactStagingDirectory)/bgmi-$(Agent.OS).zip
            replaceExistingArchive: true
            verbose: true  # Optional

        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: $(Build.ArtifactStagingDirectory)
            artifactName: binary
