jobs:
  - job: 'Lint'
    pool:
      vmImage: 'ubuntu-18.04'

    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'

    steps:
      - template: /.ci/templates/install-project.yaml
        parameters:
          python_version: $(python.version)

      - template: python/pre-commit.yaml@trim21
