jobs:
  - template: /.ci/templates/job.yaml
    parameters:
      name: pypi
      pythonVersions: ['3.7']
      images:
        - ubuntu
      steps:
        - script: poetry build
        - script: |
            pip install twine
            twine check dist/*
