jobs:
  - job: Github
    pool:
      vmImage: ubuntu-latest

    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: current
          artifactName: binary
          downloadPath: $(System.ArtifactsDirectory)

      - task: GitHubRelease@0
        inputs:
          gitHubConnection: github release
          repositoryName: $(Build.Repository.Name)
          action: create
          target: $(Build.SourceVersion)
          tagPattern: .*
          tag: $(Build.SourceBranchName)
          assets: $(Build.ArtifactStagingDirectory)/*/*
          assetUploadMode: replace
