jobs:
  - template: /.ci/templates/job.yaml
    parameters:
      name: Test
      steps:
        - bash: |
            set -ex
            coverage run -a -m bgmi.main install
            bgmi -h
            cp tests/test_script.py $HOME/.bgmi/scripts/test_script.py
            coverage run -a -m pytest tests

        - bash: bash <(curl -s https://codecov.io/bash)
