jobs:
  - template: /.ci/templates/job.yaml
    parameters:
      name: Test
      steps:
        - bash: |
            set -ex
            coverage run -a -m bgmi.main install
            bgmi -h
            cp tests/test_script.py $BGMI_PATH/scripts/test_script.py
            coverage run -a -m pytest tests --cache-requests
          env:
            DEBUG: mikan,dump
            BGMI_PATH: $(Pipeline.Workspace)/.bgmi

        - task: PublishBuildArtifacts@1
          condition: always()
          inputs:
            pathToPublish: $(Pipeline.Workspace)/.bgmi/tmp
            artifactName: tmp-$(platform)-$(python_version)

        - bash: |
            export BUILD_SOURCEBRANCHNAME=${BRANCH#"refs/heads/"} # fix azure branch source name
            bash <(curl -s https://codecov.io/bash) -Z -F "py${PYV/./}" -F "${PLATFORM}" -C $(Build.SourceVersion)
          name: Codecov
          env:
            PYV: $(python_version)
            BRANCH: $(Build.SourceBranch)
            PLATFORM: $(platform)
