name: lint

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - uses: Trim21/setup-poetry@dist/v1

      - uses: Trim21/install-poetry-project@dist/v1

      - name: flake8
        run: "flake8 --format='::error file=%(path)s,line=%(row)d,col=%(col)d::[%(code)s]: %(text)s'"

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - uses: Trim21/setup-poetry@dist/v1
      - uses: Trim21/install-poetry-project@dist/v1
      - name: add matcher
        run: echo "::add-matcher::.github/matcher/pylint.json"
      - name: pylint
        run: pylint ./bgmi

  mypy:
    runs-on: ${{ format('{0}-latest', matrix.os) }}
    strategy:
      matrix:
        python: ["3.7", "3.9"]
        os: [macos, windows, ubuntu]
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/checkout@v3
      - uses: Trim21/setup-poetry@dist/v1
      - uses: Trim21/install-poetry-project@dist/v1
      - uses: liskin/gh-problem-matcher-wrap@v1
        with:
          action: add
          linters: mypy

      - name: mypy
        run: |
          if [[ "${{ matrix.os }}" == "windows" ]]
          then
              v="true"
          else
              v="false"
          fi
          mypy --show-column-numbers "--always-$v=IS_WINDOWS" bgmi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - uses: Trim21/setup-poetry@dist/v1
      - uses: Trim21/install-poetry-project@dist/v1
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: precommit-2-${{ env.PY }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: precommit-2-${{ env.PY }}-

      - name: pre-commit
        run: pre-commit run --all-files --show-diff-on-failure && pre-commit gc
